### ISSUE TITLE
Change link in repo description to https

### ISSUE THREAD

**Issue by dwijnand** [larsrh/libisabelle#65]
You should change the link in the description from http://lars.hupel.info/libisabelle, which rendered poorly, to https://lars.hupel.info/libisabelle/ which looks awesome.

I only found out because the README links to the nice https link. In addition (or alternatively) you can make the, I assume, CSS work in http.

**Comment by larsrh** [comment]
Thanks, fixed. The cause wasn't HTTPS by the way, it was a missing trailing slash.

**Comment by dwijnand** [comment]
Ah right. Damn this trailing <x> micro-management! 😛

**Comment by larsrh** [comment]
Netlify is cool and all but I haven't yet figured out how to get it to insert appropriate trailing slashes. Nothing beats the raw power of `mod_rewrite` :smile:
