### ISSUE TITLE
etc/components not cleaned up

### ISSUE THREAD

**Issue by dominique-unruh** [larsrh/libisabelle#66]
In certain cases, libisabelle fails to remove etc/components.
The consequence is that subsequent builds of Isabelle fail.
The following sequence of commands leads to that error (with libisabelle 0.9.2)

      val version = Version.Stable("2017")
      val localStoragePath = Paths.get("/tmp/isabelle-temp")

      val platform : Platform = Platform.guess match {
        case Some(p) => p.withLocalStorage(localStoragePath)
      }

      val setup : Setup = Setup(Paths.get("/tmp/xxx"), platform, version)

      val resources = Resources.dumpIsabelleResources() match {
        case Right(r) => r
      }

      val environment = Await.result(setup.makeEnvironment(resources, Nil), Duration.Inf)

Now there is a file `/tmp/isabelle-temp/user/Isabelle2017/.isabelle/Isabelle2017/etc/components` (that should be removed by an invocation of `Environment.cleanEtcComponents()`).

**Comment by larsrh** [comment]
I can't reproduce this problem locally, as the `etc/components` gets cleared during `setup.makeEnvironment`.

Would it be possible for you to attach the detailed debug trace? Depending on which log framework you use, you should enable `trace` level to get all details. I have a hunch what the problem might be, and it should manifest itself as a warning plus a subsequent info line.

**Comment by dominique-unruh** [comment]
The log is here: [log.txt](https://github.com/larsrh/libisabelle/files/1959247/log.txt)

**Comment by larsrh** [comment]
That's what I thought. There's an error in bootstrapping:

```
Caused by: java.io.IOException: Cannot run program "/tmp/xxx/bin/isabelle": error=2, No such file or directory
```

Are you sure there's an Isabelle installation available there? Or is you point that even though the bootstrapping fails, the `etc/components` file should get cleaned up? (I agree, that's a bug.)

**Comment by dominique-unruh** [comment]
There is no installation at that point, the failure was expected. My point was the missing cleanup in the failure case. (In my setting, the failure happens intentionally in one unit test to check for correct handling of the error, and then subsequent unrelated unit tests failed.)

**Comment by larsrh** [comment]
Right. #67 will fix this.

**Comment by larsrh** [comment]
0.9.3 contains the fix.

**Comment by dominique-unruh** [comment]
I confirm that it works for me now with 0.9.3.
