### ISSUE TITLE
2018-RC1 incompatibility

### ISSUE THREAD

**Issue by dominique-unruh** [larsrh/libisabelle#70]
I think there is an incompatibility between Isabelle 2018-RC1 and libisabelle-1.0.0-RC2.
From the build process:

```
### theory "Protocol.Common"
### 0.270s elapsed time, 0.475s cpu time, 0.000s GC time
*** Failed to load theory "Protocol.Codec_Class" (unresolved "Classy.Classy")
*** Failed to load theory "Protocol.Protocol" (unresolved "Protocol.Codec_Class")
*** Failed to load theory "HOL-Protocol.HOL_Operations" (unresolved "Protocol.Protocol")
*** Failed to load theory "Protocol.ML_Expr" (unresolved "Protocol.Protocol")
*** Failed to load theory "Protocol.Basic" (unresolved "Protocol.Protocol")
*** Failed to load theory "HOL-Protocol.Protocol_Main" (unresolved "HOL-Protocol.HOL_Operations", "Protocol.Basic", "Protocol.ML_Expr")
*** Failed to load theory "QRHL-Protocol.QRHL_Operations" (unresolved "HOL-Protocol.Protocol_Main")
*** ML error (line 199 of "/tmp/libisabelle_resources5894943446203832053/classy/ml_types.ML"):
*** Value or constructor (ml_env_context) has not been declared
*** ML error (line 206 of "/tmp/libisabelle_resources5894943446203832053/classy/ml_types.ML"):
*** Value or constructor (context_set_thread_data) has not been declared
*** ML error (line 207 of "/tmp/libisabelle_resources5894943446203832053/classy/ml_types.ML"):
*** Value or constructor (secure_use_text) has not been declared
*** At command "ML_file" (line 45 of "/tmp/libisabelle_resources5894943446203832053/classy/Classy.thy")
[main] DEBUG info.hupel.isabelle.api.Environment - QRHL-Protocol: Unfinished session(s): QRHL-Protocol
```

I am not 100% sure it's libisabelle's fault, but it happened when I changed the Isabelle version from 2018-RC0 to 2018-RC1.

**Comment by dominique-unruh** [comment]
Classy.thy (as automatically included in the resources directory) contains the line `ML_cond ("2017", "2018-RC0")` which should probably include RC1 as well.

**Comment by larsrh** [comment]
Good point. I completely forgot to remove that in [classy](https://github.com/larsrh/classy). When the build for that goes through I'll release a fix.

**Comment by dominique-unruh** [comment]
Perhaps it would be easiest to already add RC2, RC3, ... and Isabelle2018 in the conditional?
That way you don't need a new release each time, if I understand the process correctly.

**Comment by larsrh** [comment]
No, that's not necessary. I removed the entire conditional block. The code for 2017+ is identical, only the older versions required different code. See [this commit](https://github.com/larsrh/classy/commit/21ef0ca4d68d5af407d383d90765bcf0193137ad).

**Comment by dominique-unruh** [comment]
Even simpler. :)

**Comment by larsrh** [comment]
Try overriding the classy version like so:

```scala
libraryDependencies ++= Seq(
  "info.hupel" % "classy" % "0.2.1",
  "info.hupel" % "multi-isabelle" % "0.1.1"
)
```

(The second one may not be necessary.)

**Comment by larsrh** [comment]
Next RC will include 84b4f18c24ea03f3bb0999bd6ed0c08d5afc0293 that fixes this problem, but the above workaround should hopefully work for now.

**Comment by dominique-unruh** [comment]
I confirm that the workaround works.
