### ISSUE TITLE
Local storage cannot be symlinked

### ISSUE THREAD

**Issue by dominique-unruh** [larsrh/libisabelle#71]
When the local storage path (configured, e.g., via `Platform.withLocalStorage`) is a symlink to an existing directory, `Setup.detect` fails with a `FileAlreadyExistsException`.

This is because `Platform.acquireLock` calls `Files.createDirectories` which (in accordance with its Javadoc description) fails when the directory already exists but is not a directory (but a symlink).

A fix should probably be to prefix the call to `Files.createDirectories`with `if (!Files.isDirectory(localStorage))`
(see https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#isDirectory(java.nio.file.Path,%20java.nio.file.LinkOption...) )

**Comment by larsrh** [comment]
Thanks, fixed in 69b413cd53899cdb9c0a8498cb747e64612f2ec2.

**Comment by larsrh** [comment]
Released as RC3.
