### ISSUE TITLE
Detection whether theory Protocol loaded does not work

### ISSUE THREAD

**Issue by dominique-unruh** [larsrh/libisabelle#72]
When starting an Isabelle session (using Isabelle 2018), the message "Protocol theory not contained in image, scheduling to be loaded ..." is logged. If the resource component is not loaded, there is even an error "protocol not loaded but component not registered", even if the Protocol theory is in the session image.

I suspect the reason is the check
```
    if (loaded.contains("Protocol"))
```
in `info.hupel.isabelle.api.Environment.protocolTheory`. I assume it should be "Protocol.Protocol" for Isabelle 2018.

**Comment by larsrh** [comment]
Thanks for the report. Fixed in 42b1a648c0cf5c1f8dcb5906db34b7c95bc579fb, `1.0.1` on its way.
