### ISSUE TITLE
Runtime extensibility of Codec.exn

### ISSUE THREAD

**Issue by dominique-unruh** [larsrh/libisabelle#73]
Currently, exceptions thrown in operations are encoded using `Codec.exn` before being sent to the invoking Scala code. `Codec.exn` basically just uses `@{make_string}`. This is a useful default for unknown exceptions, but it means that we can get quite unreadable error messages on the Scala side, such as `Par_Exn [CONTEXT (<context>, ERROR "Failed to apply initial proof method <markup>:\n<markup>")]`.

To avoid this, it would be useful to be able to overwrite behavior of `Codec.exn`. Two solutions come to mind:
* Very simple: `Codec.string_of_exn` is made into a reference, and a function is exported in `Codec` that allows to replace `Codec.string_of_exn` with own code. (This might not be the nicest way but it would be sufficient for my purposes.)
* Better, slightly more complex: Add a function for converting exceptions to string in `Codec`, and `Codec.string_of_exn` simply uses the first function that returns `SOME string`. @{make_string} is used as a fallback.

**Comment by larsrh** [comment]
I could see a combination of this:

```sml
val exn_funs: (exn -> string option) list ref
```

User code can add rendering functions. The codec remains parametrized and tries all renderers in order.

**Comment by dominique-unruh** [comment]
That is more or less what I thought of in the second solution, except that an function for atomic appending to that list is exported, but not exn_funs itself (for thread safety, and to reduce the chance that different theories mess up each others handlers). But at least in my use case it doesn't make a difference because I'd have just one place which accesses this list.

**Comment by larsrh** [comment]
Yes, makes sense. Are you willing to submit a patch?
